//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserQuestionsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userQuestions
    {
        public int id { get; set; }
        public string userQuestion { get; set; }
        public string userIp { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
